title: Qi LIU (Elly) # your name (or website title) here
logo: "/images/Q.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Regional Manager (User Growth), LAZADA 
  <br><br>
  Product Analytics, Customer Analytics, User Growth, Game
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0

